version: '3.3'
   
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpresspcc
       MYSQL_DATABASE: wordpresspcc
       MYSQL_USER: pcc
       MYSQL_PASSWORD: wordpresspcc
   
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: pcc
       WORDPRESS_DB_PASSWORD: wordpresspcc
       WORDPRESS_DB_NAME: wordpresspcc
volumes:
    db_data: {}

